# Funding

If you find KALA helpful, consider supporting the project:

github: [haysan]
# patreon: your-patreon-username
# open_collective: your-opencollective-username
# ko_fi: your-kofi-username
# custom: ["https://your-donation-link.com"]
